# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SaveAsCSV
                                 A QGIS plugin
 This plugin coverts vector data to csv
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-03-16
        copyright            : (C) 2022 by Brenda Chepngetich
        email                : brendabre18@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Brenda Chepngetich'
__date__ = '2022-03-16'
__copyright__ = '(C) 2022 by Brenda Chepngetich'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SaveAsCSV class from file SaveAsCSV.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .saveascsv import SaveAsCSVPlugin
    return SaveAsCSVPlugin()
